### ISSUE TITLE
treating a filter like an action

### ISSUE THREAD

**Issue by joyously** [azurecurve/azrcrv-gallery-from-folder#1]
'the_posts' is actually a filter. While actions and filters are similar and it works to use `add_action` instead of `add_filter`, it is confusing and misleading to treat it like an action, but have to return the value because it's actually a filter.

https://github.com/azurecurve/azrcrv-gallery-from-folder/blob/5ec12dcd9f8cb63c2720b3ab7be9cef72a2849b0/azrcrv-gallery-from-folder.php#L42

**Comment by azurecurve** [comment]
Ok, I can change.
