### ISSUE TITLE
admin URL

### ISSUE THREAD

**Issue by joyously** [azurecurve/azrcrv-gallery-from-folder#2]
https://github.com/azurecurve/azrcrv-gallery-from-folder/blob/5ec12dcd9f8cb63c2720b3ab7be9cef72a2849b0/azrcrv-gallery-from-folder.php#L221

This won't work for people that change their admin folder location.
You could use `admin_url()`
https://developer.wordpress.org/reference/functions/admin_url/

**Comment by azurecurve** [comment]
Yes, I can change this.
