### ISSUE TITLE
use proper sanitize function

### ISSUE THREAD

**Issue by joyously** [azurecurve/azrcrv-gallery-from-folder#3]
https://github.com/azurecurve/azrcrv-gallery-from-folder/blob/5ec12dcd9f8cb63c2720b3ab7be9cef72a2849b0/azrcrv-gallery-from-folder.php#L341

Instead of `sanitize_text_field` you should use `sanitize_file_name` for the default folder.

**Comment by joyously** [comment]
I just realized that maybe this is the path, not just a folder name. If so, you might use `wp_strip_all_tags`.
Maybe improve the instructions for what should be entered.

**Comment by azurecurve** [comment]
I'm going to rewrite the settings and path handling to be more explicit and flexible.
